spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shoppingmall
    username: root
    password:
  sql:
    init:
      data-locations: classpath:import.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
  mvc:
    static-path-pattern: '/static/**'
#    view:
#      prefix: /templates/
#      suffix: .html

#    properties:
#      hibernate:
#        format_sql: true
jwt:
  secret:

cloud:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

toss:
  secret:

server:
  port: 8080