spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall
    username: root
    password: Dbtlalal4200!
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: '/static/**'
#    view:
#      prefix: /templates/
#      suffix: .html

jwt:
  secret: dhdhdrgrjkjlfdlgjldppprpujgjlkjjldfgsg

cloud:
  aws:
    s3:
      bucket: shoppingmall-bucket-simidot
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

toss:
  secret:

server:
  port: 8080